// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SVM.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) 2017, Apple Inc. All rights reserved.
//
// Use of this source code is governed by a BSD-3-clause license that can be
// found in LICENSE.txt or at https://opensource.org/licenses/BSD-3-Clause

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///*
/// A linear kernel.
///
/// This function has the following formula:
///
/// .. math::
///     K(\boldsymbol{x}, \boldsymbol{x'}) = \boldsymbol{x}^T \boldsymbol{x'}
public struct CoreML_Specification_LinearKernel: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".LinearKernel"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A Gaussian radial basis function (RBF) kernel.
///
/// This function has the following formula:
///
/// .. math::
///     K(\boldsymbol{x}, \boldsymbol{x'}) = \
///          \exp(-\gamma || \boldsymbol{x} - \boldsymbol{x'} ||^2 )
public struct CoreML_Specification_RBFKernel: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RBFKernel"

  public var gamma: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.gamma)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.gamma != 0 {
      try visitor.visitSingularDoubleField(value: self.gamma, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A polynomial kernel.
///
/// This function has the following formula:
///
/// .. math::
///     K(\boldsymbol{x}, \boldsymbol{x'}) = \
///           (\gamma \boldsymbol{x}^T \boldsymbol{x'} + c)^{degree}
public struct CoreML_Specification_PolyKernel: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".PolyKernel"

  public var degree: Int32 = 0

  public var c: Double = 0

  public var gamma: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.degree)
      case 2: try decoder.decodeSingularDoubleField(value: &self.c)
      case 3: try decoder.decodeSingularDoubleField(value: &self.gamma)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.degree != 0 {
      try visitor.visitSingularInt32Field(value: self.degree, fieldNumber: 1)
    }
    if self.c != 0 {
      try visitor.visitSingularDoubleField(value: self.c, fieldNumber: 2)
    }
    if self.gamma != 0 {
      try visitor.visitSingularDoubleField(value: self.gamma, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A sigmoid kernel.
///
/// This function has the following formula:
///
/// .. math::
///     K(\boldsymbol{x}, \boldsymbol{x'}) = \
///           \tanh(\gamma \boldsymbol{x}^T \boldsymbol{x'} + c)
public struct CoreML_Specification_SigmoidKernel: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".SigmoidKernel"

  public var gamma: Double = 0

  public var c: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.gamma)
      case 2: try decoder.decodeSingularDoubleField(value: &self.c)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.gamma != 0 {
      try visitor.visitSingularDoubleField(value: self.gamma, fieldNumber: 1)
    }
    if self.c != 0 {
      try visitor.visitSingularDoubleField(value: self.c, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A kernel.
public struct CoreML_Specification_Kernel: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".Kernel"

  public var kernel: OneOf_Kernel? {
    get {return _storage._kernel}
    set {_uniqueStorage()._kernel = newValue}
  }

  public var linearKernel: CoreML_Specification_LinearKernel {
    get {
      if case .linearKernel(let v)? = _storage._kernel {return v}
      return CoreML_Specification_LinearKernel()
    }
    set {_uniqueStorage()._kernel = .linearKernel(newValue)}
  }

  public var rbfKernel: CoreML_Specification_RBFKernel {
    get {
      if case .rbfKernel(let v)? = _storage._kernel {return v}
      return CoreML_Specification_RBFKernel()
    }
    set {_uniqueStorage()._kernel = .rbfKernel(newValue)}
  }

  public var polyKernel: CoreML_Specification_PolyKernel {
    get {
      if case .polyKernel(let v)? = _storage._kernel {return v}
      return CoreML_Specification_PolyKernel()
    }
    set {_uniqueStorage()._kernel = .polyKernel(newValue)}
  }

  public var sigmoidKernel: CoreML_Specification_SigmoidKernel {
    get {
      if case .sigmoidKernel(let v)? = _storage._kernel {return v}
      return CoreML_Specification_SigmoidKernel()
    }
    set {_uniqueStorage()._kernel = .sigmoidKernel(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Kernel: Equatable {
    case linearKernel(CoreML_Specification_LinearKernel)
    case rbfKernel(CoreML_Specification_RBFKernel)
    case polyKernel(CoreML_Specification_PolyKernel)
    case sigmoidKernel(CoreML_Specification_SigmoidKernel)

    public static func ==(lhs: CoreML_Specification_Kernel.OneOf_Kernel, rhs: CoreML_Specification_Kernel.OneOf_Kernel) -> Bool {
      switch (lhs, rhs) {
      case (.linearKernel(let l), .linearKernel(let r)): return l == r
      case (.rbfKernel(let l), .rbfKernel(let r)): return l == r
      case (.polyKernel(let l), .polyKernel(let r)): return l == r
      case (.sigmoidKernel(let l), .sigmoidKernel(let r)): return l == r
      default: return false
      }
    }
  }

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1:
          var v: CoreML_Specification_LinearKernel?
          if let current = _storage._kernel {
            try decoder.handleConflictingOneOf()
            if case .linearKernel(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._kernel = .linearKernel(v)}
        case 2:
          var v: CoreML_Specification_RBFKernel?
          if let current = _storage._kernel {
            try decoder.handleConflictingOneOf()
            if case .rbfKernel(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._kernel = .rbfKernel(v)}
        case 3:
          var v: CoreML_Specification_PolyKernel?
          if let current = _storage._kernel {
            try decoder.handleConflictingOneOf()
            if case .polyKernel(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._kernel = .polyKernel(v)}
        case 4:
          var v: CoreML_Specification_SigmoidKernel?
          if let current = _storage._kernel {
            try decoder.handleConflictingOneOf()
            if case .sigmoidKernel(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._kernel = .sigmoidKernel(v)}
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      switch _storage._kernel {
      case .linearKernel(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      case .rbfKernel(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      case .polyKernel(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      case .sigmoidKernel(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

///*
/// A sparse node.
public struct CoreML_Specification_SparseNode: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".SparseNode"

  /// 1-based indexes, like libsvm
  public var index: Int32 = 0

  public var value: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.index)
      case 2: try decoder.decodeSingularDoubleField(value: &self.value)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularDoubleField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A sparse vector.
public struct CoreML_Specification_SparseVector: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".SparseVector"

  public var nodes: [CoreML_Specification_SparseNode] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.nodes)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nodes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.nodes, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// One or more sparse support vectors.
public struct CoreML_Specification_SparseSupportVectors: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".SparseSupportVectors"

  public var vectors: [CoreML_Specification_SparseVector] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.vectors)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vectors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vectors, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A dense vector.
public struct CoreML_Specification_DenseVector: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".DenseVector"

  public var values: [Double] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedDoubleField(value: &self.values)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitPackedDoubleField(value: self.values, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// One or more dense support vectors.
public struct CoreML_Specification_DenseSupportVectors: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".DenseSupportVectors"

  public var vectors: [CoreML_Specification_DenseVector] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.vectors)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.vectors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vectors, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// One or more coefficients.
public struct CoreML_Specification_Coefficients: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".Coefficients"

  public var alpha: [Double] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedDoubleField(value: &self.alpha)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.alpha.isEmpty {
      try visitor.visitPackedDoubleField(value: self.alpha, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

///*
/// A support vector regressor.
public struct CoreML_Specification_SupportVectorRegressor: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".SupportVectorRegressor"

  public var kernel: CoreML_Specification_Kernel {
    get {return _storage._kernel ?? CoreML_Specification_Kernel()}
    set {_uniqueStorage()._kernel = newValue}
  }
  /// Returns true if `kernel` has been explicitly set.
  public var hasKernel: Bool {return _storage._kernel != nil}
  /// Clears the value of `kernel`. Subsequent reads from it will return its default value.
  public mutating func clearKernel() {_storage._kernel = nil}

  /// Support vectors, either sparse or dense format
  public var supportVectors: OneOf_SupportVectors? {
    get {return _storage._supportVectors}
    set {_uniqueStorage()._supportVectors = newValue}
  }

  public var sparseSupportVectors: CoreML_Specification_SparseSupportVectors {
    get {
      if case .sparseSupportVectors(let v)? = _storage._supportVectors {return v}
      return CoreML_Specification_SparseSupportVectors()
    }
    set {_uniqueStorage()._supportVectors = .sparseSupportVectors(newValue)}
  }

  public var denseSupportVectors: CoreML_Specification_DenseSupportVectors {
    get {
      if case .denseSupportVectors(let v)? = _storage._supportVectors {return v}
      return CoreML_Specification_DenseSupportVectors()
    }
    set {_uniqueStorage()._supportVectors = .denseSupportVectors(newValue)}
  }

  /// Coefficients, one for each support vector
  public var coefficients: CoreML_Specification_Coefficients {
    get {return _storage._coefficients ?? CoreML_Specification_Coefficients()}
    set {_uniqueStorage()._coefficients = newValue}
  }
  /// Returns true if `coefficients` has been explicitly set.
  public var hasCoefficients: Bool {return _storage._coefficients != nil}
  /// Clears the value of `coefficients`. Subsequent reads from it will return its default value.
  public mutating func clearCoefficients() {_storage._coefficients = nil}

  public var rho: Double {
    get {return _storage._rho}
    set {_uniqueStorage()._rho = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Support vectors, either sparse or dense format
  public enum OneOf_SupportVectors: Equatable {
    case sparseSupportVectors(CoreML_Specification_SparseSupportVectors)
    case denseSupportVectors(CoreML_Specification_DenseSupportVectors)

    public static func ==(lhs: CoreML_Specification_SupportVectorRegressor.OneOf_SupportVectors, rhs: CoreML_Specification_SupportVectorRegressor.OneOf_SupportVectors) -> Bool {
      switch (lhs, rhs) {
      case (.sparseSupportVectors(let l), .sparseSupportVectors(let r)): return l == r
      case (.denseSupportVectors(let l), .denseSupportVectors(let r)): return l == r
      default: return false
      }
    }
  }

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._kernel)
        case 2:
          var v: CoreML_Specification_SparseSupportVectors?
          if let current = _storage._supportVectors {
            try decoder.handleConflictingOneOf()
            if case .sparseSupportVectors(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._supportVectors = .sparseSupportVectors(v)}
        case 3:
          var v: CoreML_Specification_DenseSupportVectors?
          if let current = _storage._supportVectors {
            try decoder.handleConflictingOneOf()
            if case .denseSupportVectors(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._supportVectors = .denseSupportVectors(v)}
        case 4: try decoder.decodeSingularMessageField(value: &_storage._coefficients)
        case 5: try decoder.decodeSingularDoubleField(value: &_storage._rho)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._kernel {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      switch _storage._supportVectors {
      case .sparseSupportVectors(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      case .denseSupportVectors(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      case nil: break
      }
      if let v = _storage._coefficients {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if _storage._rho != 0 {
        try visitor.visitSingularDoubleField(value: _storage._rho, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

///*
/// A support vector classifier
public struct CoreML_Specification_SupportVectorClassifier: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".SupportVectorClassifier"

  public var kernel: CoreML_Specification_Kernel {
    get {return _storage._kernel ?? CoreML_Specification_Kernel()}
    set {_uniqueStorage()._kernel = newValue}
  }
  /// Returns true if `kernel` has been explicitly set.
  public var hasKernel: Bool {return _storage._kernel != nil}
  /// Clears the value of `kernel`. Subsequent reads from it will return its default value.
  public mutating func clearKernel() {_storage._kernel = nil}

  ///*
  /// The number of support vectors for each class.
  public var numberOfSupportVectorsPerClass: [Int32] {
    get {return _storage._numberOfSupportVectorsPerClass}
    set {_uniqueStorage()._numberOfSupportVectorsPerClass = newValue}
  }

  ///*
  /// The support vectors, in either sparse or dense format.
  public var supportVectors: OneOf_SupportVectors? {
    get {return _storage._supportVectors}
    set {_uniqueStorage()._supportVectors = newValue}
  }

  public var sparseSupportVectors: CoreML_Specification_SparseSupportVectors {
    get {
      if case .sparseSupportVectors(let v)? = _storage._supportVectors {return v}
      return CoreML_Specification_SparseSupportVectors()
    }
    set {_uniqueStorage()._supportVectors = .sparseSupportVectors(newValue)}
  }

  public var denseSupportVectors: CoreML_Specification_DenseSupportVectors {
    get {
      if case .denseSupportVectors(let v)? = _storage._supportVectors {return v}
      return CoreML_Specification_DenseSupportVectors()
    }
    set {_uniqueStorage()._supportVectors = .denseSupportVectors(newValue)}
  }

  ///*
  /// The coefficients, essentially a two dimensional array of
  /// size: (numberOfClasses-1) by (total number of support vectors)
  public var coefficients: [CoreML_Specification_Coefficients] {
    get {return _storage._coefficients}
    set {_uniqueStorage()._coefficients = newValue}
  }

  ///*
  /// Constants for decision function,
  /// with K*(K-1) / 2 elements,
  /// where K is the number of classes.
  public var rho: [Double] {
    get {return _storage._rho}
    set {_uniqueStorage()._rho = newValue}
  }

  ///*
  /// Pairwise probability information for A vs B classifier.
  /// Total of K*(K-1)/2 elements where K is the number of classes.
  /// These fields are optional,
  /// and only required if you want probabilities or multi class predictions.
  public var probA: [Double] {
    get {return _storage._probA}
    set {_uniqueStorage()._probA = newValue}
  }

  public var probB: [Double] {
    get {return _storage._probB}
    set {_uniqueStorage()._probB = newValue}
  }

  ///*
  /// Class label mapping.
  public var classLabels: OneOf_ClassLabels? {
    get {return _storage._classLabels}
    set {_uniqueStorage()._classLabels = newValue}
  }

  public var stringClassLabels: CoreML_Specification_StringVector {
    get {
      if case .stringClassLabels(let v)? = _storage._classLabels {return v}
      return CoreML_Specification_StringVector()
    }
    set {_uniqueStorage()._classLabels = .stringClassLabels(newValue)}
  }

  public var int64ClassLabels: CoreML_Specification_Int64Vector {
    get {
      if case .int64ClassLabels(let v)? = _storage._classLabels {return v}
      return CoreML_Specification_Int64Vector()
    }
    set {_uniqueStorage()._classLabels = .int64ClassLabels(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  ///*
  /// The support vectors, in either sparse or dense format.
  public enum OneOf_SupportVectors: Equatable {
    case sparseSupportVectors(CoreML_Specification_SparseSupportVectors)
    case denseSupportVectors(CoreML_Specification_DenseSupportVectors)

    public static func ==(lhs: CoreML_Specification_SupportVectorClassifier.OneOf_SupportVectors, rhs: CoreML_Specification_SupportVectorClassifier.OneOf_SupportVectors) -> Bool {
      switch (lhs, rhs) {
      case (.sparseSupportVectors(let l), .sparseSupportVectors(let r)): return l == r
      case (.denseSupportVectors(let l), .denseSupportVectors(let r)): return l == r
      default: return false
      }
    }
  }

  ///*
  /// Class label mapping.
  public enum OneOf_ClassLabels: Equatable {
    case stringClassLabels(CoreML_Specification_StringVector)
    case int64ClassLabels(CoreML_Specification_Int64Vector)

    public static func ==(lhs: CoreML_Specification_SupportVectorClassifier.OneOf_ClassLabels, rhs: CoreML_Specification_SupportVectorClassifier.OneOf_ClassLabels) -> Bool {
      switch (lhs, rhs) {
      case (.stringClassLabels(let l), .stringClassLabels(let r)): return l == r
      case (.int64ClassLabels(let l), .int64ClassLabels(let r)): return l == r
      default: return false
      }
    }
  }

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._kernel)
        case 2: try decoder.decodeRepeatedInt32Field(value: &_storage._numberOfSupportVectorsPerClass)
        case 3:
          var v: CoreML_Specification_SparseSupportVectors?
          if let current = _storage._supportVectors {
            try decoder.handleConflictingOneOf()
            if case .sparseSupportVectors(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._supportVectors = .sparseSupportVectors(v)}
        case 4:
          var v: CoreML_Specification_DenseSupportVectors?
          if let current = _storage._supportVectors {
            try decoder.handleConflictingOneOf()
            if case .denseSupportVectors(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._supportVectors = .denseSupportVectors(v)}
        case 5: try decoder.decodeRepeatedMessageField(value: &_storage._coefficients)
        case 6: try decoder.decodeRepeatedDoubleField(value: &_storage._rho)
        case 7: try decoder.decodeRepeatedDoubleField(value: &_storage._probA)
        case 8: try decoder.decodeRepeatedDoubleField(value: &_storage._probB)
        case 100:
          var v: CoreML_Specification_StringVector?
          if let current = _storage._classLabels {
            try decoder.handleConflictingOneOf()
            if case .stringClassLabels(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._classLabels = .stringClassLabels(v)}
        case 101:
          var v: CoreML_Specification_Int64Vector?
          if let current = _storage._classLabels {
            try decoder.handleConflictingOneOf()
            if case .int64ClassLabels(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._classLabels = .int64ClassLabels(v)}
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._kernel {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._numberOfSupportVectorsPerClass.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._numberOfSupportVectorsPerClass, fieldNumber: 2)
      }
      switch _storage._supportVectors {
      case .sparseSupportVectors(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      case .denseSupportVectors(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      case nil: break
      }
      if !_storage._coefficients.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._coefficients, fieldNumber: 5)
      }
      if !_storage._rho.isEmpty {
        try visitor.visitPackedDoubleField(value: _storage._rho, fieldNumber: 6)
      }
      if !_storage._probA.isEmpty {
        try visitor.visitPackedDoubleField(value: _storage._probA, fieldNumber: 7)
      }
      if !_storage._probB.isEmpty {
        try visitor.visitPackedDoubleField(value: _storage._probB, fieldNumber: 8)
      }
      switch _storage._classLabels {
      case .stringClassLabels(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
      case .int64ClassLabels(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "CoreML.Specification"

extension CoreML_Specification_LinearKernel: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_LinearKernel) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_RBFKernel: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "gamma"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_RBFKernel) -> Bool {
    if self.gamma != other.gamma {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_PolyKernel: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "degree"),
    2: .same(proto: "c"),
    3: .same(proto: "gamma"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_PolyKernel) -> Bool {
    if self.degree != other.degree {return false}
    if self.c != other.c {return false}
    if self.gamma != other.gamma {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_SigmoidKernel: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "gamma"),
    2: .same(proto: "c"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_SigmoidKernel) -> Bool {
    if self.gamma != other.gamma {return false}
    if self.c != other.c {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_Kernel: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "linearKernel"),
    2: .same(proto: "rbfKernel"),
    3: .same(proto: "polyKernel"),
    4: .same(proto: "sigmoidKernel"),
  ]

  fileprivate class _StorageClass {
    var _kernel: CoreML_Specification_Kernel.OneOf_Kernel?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _kernel = source._kernel
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_Kernel) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._kernel != other_storage._kernel {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_SparseNode: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "index"),
    2: .same(proto: "value"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_SparseNode) -> Bool {
    if self.index != other.index {return false}
    if self.value != other.value {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_SparseVector: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "nodes"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_SparseVector) -> Bool {
    if self.nodes != other.nodes {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_SparseSupportVectors: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "vectors"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_SparseSupportVectors) -> Bool {
    if self.vectors != other.vectors {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_DenseVector: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "values"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_DenseVector) -> Bool {
    if self.values != other.values {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_DenseSupportVectors: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "vectors"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_DenseSupportVectors) -> Bool {
    if self.vectors != other.vectors {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_Coefficients: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "alpha"),
  ]

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_Coefficients) -> Bool {
    if self.alpha != other.alpha {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_SupportVectorRegressor: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "kernel"),
    2: .same(proto: "sparseSupportVectors"),
    3: .same(proto: "denseSupportVectors"),
    4: .same(proto: "coefficients"),
    5: .same(proto: "rho"),
  ]

  fileprivate class _StorageClass {
    var _kernel: CoreML_Specification_Kernel? = nil
    var _supportVectors: CoreML_Specification_SupportVectorRegressor.OneOf_SupportVectors?
    var _coefficients: CoreML_Specification_Coefficients? = nil
    var _rho: Double = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _kernel = source._kernel
      _supportVectors = source._supportVectors
      _coefficients = source._coefficients
      _rho = source._rho
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_SupportVectorRegressor) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._kernel != other_storage._kernel {return false}
        if _storage._supportVectors != other_storage._supportVectors {return false}
        if _storage._coefficients != other_storage._coefficients {return false}
        if _storage._rho != other_storage._rho {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension CoreML_Specification_SupportVectorClassifier: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "kernel"),
    2: .same(proto: "numberOfSupportVectorsPerClass"),
    3: .same(proto: "sparseSupportVectors"),
    4: .same(proto: "denseSupportVectors"),
    5: .same(proto: "coefficients"),
    6: .same(proto: "rho"),
    7: .same(proto: "probA"),
    8: .same(proto: "probB"),
    100: .same(proto: "stringClassLabels"),
    101: .same(proto: "int64ClassLabels"),
  ]

  fileprivate class _StorageClass {
    var _kernel: CoreML_Specification_Kernel? = nil
    var _numberOfSupportVectorsPerClass: [Int32] = []
    var _supportVectors: CoreML_Specification_SupportVectorClassifier.OneOf_SupportVectors?
    var _coefficients: [CoreML_Specification_Coefficients] = []
    var _rho: [Double] = []
    var _probA: [Double] = []
    var _probB: [Double] = []
    var _classLabels: CoreML_Specification_SupportVectorClassifier.OneOf_ClassLabels?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _kernel = source._kernel
      _numberOfSupportVectorsPerClass = source._numberOfSupportVectorsPerClass
      _supportVectors = source._supportVectors
      _coefficients = source._coefficients
      _rho = source._rho
      _probA = source._probA
      _probB = source._probB
      _classLabels = source._classLabels
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: CoreML_Specification_SupportVectorClassifier) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._kernel != other_storage._kernel {return false}
        if _storage._numberOfSupportVectorsPerClass != other_storage._numberOfSupportVectorsPerClass {return false}
        if _storage._supportVectors != other_storage._supportVectors {return false}
        if _storage._coefficients != other_storage._coefficients {return false}
        if _storage._rho != other_storage._rho {return false}
        if _storage._probA != other_storage._probA {return false}
        if _storage._probB != other_storage._probB {return false}
        if _storage._classLabels != other_storage._classLabels {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
